// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7iV0xmsN8Z9uXrScsKsH_WjpBvLSmi0M',
    appId: '1:352020076843:web:a991e6d06fe4c17a5d0d6e',
    messagingSenderId: '352020076843',
    projectId: 'booking-app-a83f1',
    authDomain: 'booking-app-a83f1.firebaseapp.com',
    databaseURL: 'https://booking-app-a83f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'booking-app-a83f1.appspot.com',
    measurementId: 'G-C3N4KLW11S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jBMltnQnrO-sSn0KhEe4oHKtd5IUCDM',
    appId: '1:352020076843:android:f30f54e5b7f2f98b5d0d6e',
    messagingSenderId: '352020076843',
    projectId: 'booking-app-a83f1',
    databaseURL: 'https://booking-app-a83f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'booking-app-a83f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPOmyeFtOlyIKZ1IYWzAHKxaCBndadqM',
    appId: '1:352020076843:ios:421c7519c2e2cedd5d0d6e',
    messagingSenderId: '352020076843',
    projectId: 'booking-app-a83f1',
    databaseURL: 'https://booking-app-a83f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'booking-app-a83f1.appspot.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPOmyeFtOlyIKZ1IYWzAHKxaCBndadqM',
    appId: '1:352020076843:ios:757a19ebccedf18f5d0d6e',
    messagingSenderId: '352020076843',
    projectId: 'booking-app-a83f1',
    databaseURL: 'https://booking-app-a83f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'booking-app-a83f1.appspot.com',
    iosBundleId: 'com.example.booking.RunnerTests',
  );
}
